services:
  jmdots-comfyui:
    image: ${COMFYUI_IMAGE_NAME}:${COMFYUI_TAG}
    build: .
    ports:
      - "${COMFYUI_BIND_ADDRESS}:${COMFYUI_HOST_PORT}:${COMFYUI_CONTAINER_PORT}"
    volumes:
      - ${COMFYUI_VOLUME_MODELS}:/workspace/ComfyUI/models
      - ${COMFYUI_VOLUME_CUSTOM_NODES}:/workspace/ComfyUI/custom_nodes
      # Defaults to not mounted. See README.md
      #- ./extra_model_paths.yaml:/workspace/ComfyUI/extra_model_paths.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
